### ISSUE TITLE
REPL This?

### ISSUE THREAD

**Issue by aenbar** [learn-co-students/looping-loop-000#7]
This might be better to do in a repl. Or just add a test? feels weird to have labs without tests.

**Comment by markedwardmurray** [comment]
Hey Adam! Thanks for the feedback. We have an easier time seeing issues raised on the canonical repositories in learn-co-curriculum rather than on the batch repositories in learn-co-students. I transcribed it for your here: https://github.com/learn-co-curriculum/looping-loop/issues/2 . The "suggest a change" button in Learn.co now takes you directly to the issues page on the canonicals!
